[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
]

[project]
name = "django-sri"
description = "Subresource Integrity for Django"
authors = [
    {name = "Jake Howard"},
]
version = "1.0.0"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Topic :: Internet :: WWW/HTTP",
    "Typing :: Typed"
]
requires-python = ">=3.11"
dependencies = [
    "django>=5.2",
]

[project.urls]
Source = "https://github.com/RealOrangeOne/django-sri"
Issues = "https://github.com/RealOrangeOne/django-sri/issues"
Changelog = "https://github.com/RealOrangeOne/django-sri/releases"

[dependency-groups]
dev = [
    "ruff==0.16.8",
    "mypy==2.3.1",
    "django-stubs[compatible-mypy]",
    "pytest==9.1.1",
    "pytest-django==4.14.0",
    "pytest-cov==7.1.0",
    "jinja2",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
warn_unused_ignores = true
warn_return_any = true
show_error_codes = true
strict_optional = true
implicit_optional = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
check_untyped_defs = true
ignore_missing_imports = true

[tool.pytest]
DJANGO_SETTINGS_MODULE = "tests.settings"
python_files = ["tests.py"]

[tool.django-stubs]
django_settings_module = "tests.settings"

[tool.ruff.lint]
select = ["E", "F", "I", "W", "N", "B", "A", "C4", "T20", "DJ", "S", "UP"]
ignore = ["E501", "DJ008"]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["S101", "S701", "S105"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
ignore_errors = true
exclude_also = [
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain about abstract methods, they aren't run:
    "@(abc.)?abstractmethod",

    # Nor complain about type checking
    "if TYPE_CHECKING:",
]
